### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by josiahls** [rlcode/per#7]
Recommend The MIT License

**Comment by cyrilibrahim** [comment]
Hi @jcwleo , I see that you are the main contributor of this repository. I find this PER really minimalist and clear, and I would want to use it in a project, but there's still no license. I wonder, if this is wanted or not since I saw MIT licenses in other rlcode repositories. Do you plan to put a license in this repository ?

Thanks a lot!

**Comment by jcwleo** [comment]
@josiahls , Thank you. I added License.
@cyrilibrahim , I added MIT License. :)
